
server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true


spring:
  application:
    name: ageservice
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/crud4blue
    username: postgres
    password: admin
jwt:
  config:
    type: signed
